# Generated by Django 4.0.4 on 2022-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_text_1', models.CharField(blank=True, max_length=200, null=True)),
                ('short_text_2', models.CharField(blank=True, max_length=200, null=True)),
                ('short_text_3', models.CharField(blank=True, max_length=200, null=True)),
                ('short_text_4', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
